language: r

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: J33bN8jgnG4X7KserEewpPZ2rFAKiivnMlc8FOaQ/VUdlQQBJ7fNHsAIbEzchZUyxnXARnJyqP+D7nNoKQfBe7oCBuqjolgtq3VwHHT11Wwdr+B9y5sCBtYSbv2ATACWfdSjjCxFTi29HpH0jt3bSmOfs6hwlylgc7UHF0SKkNo=
