language: r
cache: packages
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel

r_github_packages:
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: J33bN8jgnG4X7KserEewpPZ2rFAKiivnMlc8FOaQ/VUdlQQBJ7fNHsAIbEzchZUyxnXARnJyqP+D7nNoKQfBe7oCBuqjolgtq3VwHHT11Wwdr+B9y5sCBtYSbv2ATACWfdSjjCxFTi29HpH0jt3bSmOfs6hwlylgc7UHF0SKkNo=
